sudo: true

env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.6.22-f9533ba-linux-amd64.tar.xz

notifications:
  email:
    recipients:
      - achaturvedi@salesforce.com
    on_success: change
    on_failure: always

before_install:
  - openssl aes-256-cbc -K $encrypted_83405c984118_key -iv $encrypted_83405c984118_iv -in assets/server.key.enc -out assets/server.key -d
  - wget -qO- $URL | tar xJf -
  - ./heroku/install
  - export PATH=./heroku/$(pwd):$PATH

before_script:
  - echo $HOME
  - cd $HOME/.local/share/sfdx/plugins/node_modules/salesforce-alm/lib/
  - pwd
  - export SFDX_DISABLE_ENCRYPTION=true
  - sfdx force --help
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername
  - sfdx force:auth:jwt:grant -i $SBOXCONSUMERKEY -f assets/server.key -u achaturvedi@dxhubprod.demo.dxhubdev

script:
  - sfdx force:org:create -s -f config/workspace-scratch-def.json -a travisciorg
  - sfdx force:source:push -u travisciorg
  - sfdx force:apex:test:run -r tap
  - sleep 2m
  - sfdx force:org:delete -u travisciorg -p
  - mkdir mdapioutput_dir
  - sfdx force:source:convert -d mdapioutput_dir/
  - sfdx force:mdapi:deploy -d mdapioutput_dir/ -u $SBOXUSERNAME